### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by willwill2will54** [NeonCrafter13/Transport-Fever-2-NeonModManager#31] opened 2021-02-24 12:29 UTC
I wonder, given the recent release of TF2 for MacOS, if Mac support is a direction you'd be willing to take this project?

If so, I'd be happy to contribute.

**Comment by NeonCrafter13** [comment] 2021-02-27 15:29
Yeah I thought about adding Mac support the problem is I don't have an Mac and I don't have any ideas how people even install apps on mac. If you want to help you can of course do so. 

I have some sys.platform == "linux"` stuff in my code so there would need to be added "darwin" i think. 

Also my code is a little mess so, if you have any questions feel free to ask.

**Comment by willwill2will54** [comment] 2021-03-20 21:50
I should have an PR up today or tomorrow

**Comment by willwill2will54** [comment] 2021-03-20 23:02
Addressed by
https://github.com/NeonCrafter13/Transport-Fever-2-NeonModManager/pull/32

**Comment by NeonCrafter13** [comment] 2021-03-23 16:48
I have merged your commit, thank you for your help.

You said you could work on app packaging for mac, can you do that, It would very generous from you. 

Do you have an account on Transportfever.net, because if you do I can add you as a contributor.

**Comment by willwill2will54** [comment] 2021-03-23 16:55
I do now! [willwill2will](https://www.transportfever.net/wsc/index.php?user/48005-willwill2will/)

**Comment by willwill2will54** [comment] 2021-03-24 23:01
App packaging is in: #33!

Obviously without a Mac system to build on, you cannot build them yourself. For the time being I can pass along my builds: [current - mega.nz](https://mega.nz/file/tlgiWCYK#1L6NV72qFWBbmS_n0gCc9VugSRCVXQdL2ExD2w-Z8CY)

However, this is logistically complex, so for the longer term if you wish I can lend a hand helping you set up a macOS virtual machine. This will not only allow you to build for Mac yourself, but is also just generally a useful capability to have.

**Comment by NeonCrafter13** [comment] 2021-03-26 22:45
I will upload the new version, I will look into setting up a mac VM.

**Closed as completed by NeonCrafter13** 2021-03-26 22:45 UTC

**Comment by NeonCrafter13** [comment] 2021-03-26 23:20
I have uploaded the new version, thanks for your help.

**Comment by NeonCrafter13** [comment] 2021-04-09 17:26
@willwill2will54 I have set up a Mac OS VM and I can run the Program but the packaging does not work.
It gives me the Error:
```
prepare_qt_app()
error: The specified item could not be found in the keychain.
error: Code signing of app bundle failed
error: The specified item could not be found in the keychain.
~/Transport-Fever-2-NeonModManager
```

What do I need to do in order to fix this. 
Or what causes the problem.

Thanks in advance

**Comment by willwill2will54** [comment] 2021-04-10 11:30
1. Install Xcode on the VM and launch it.
2. Open Xcode > Preferences > Accounts. Sign in with an Apple ID.
3. Select your 'Personal Team' and select 'Manage Certificates'
4. Ensure there is an entry under 'Apple Development Certificates
5. If not, click the '+' button to add one
6. Open the Keychain Access application, and select the login keychain.
7. Select the 'My Certificates' filter
8. Take note of the certificate name: this is probably going to be the email you used to set up the Apple ID.
![image](https://user-images.githubusercontent.com/38622599/114268027-f36ddc80-99f6-11eb-8b86-ddc9bedc07c7.png)
9. Replace my email with yours in the build script.

If there is not enough room inside the VM to install Xcode using the App Store (~25 GB), you can download it from [apple's developer site](https://developer.apple.com/download/more/?=xcode%2012.4) as a xip (yes, with an x), extract it outside and ```scp``` it in, or something like that (~15 GB).

**Comment by NeonCrafter13** [comment] 2021-05-03 15:04
@willwill2will54 
Thanks, I did everything you said but I still get an Error:
```
prepare_qt_app()
error: The specified item could not be found in the keychain.
error: Code signing of app bundle failed
Warning: unable to build chain to self-signed root for signer "Apple Development: replaced@gmail.com (replaced id)"
./build/Transport Fever 2 NeonModManager.app: errSecInternalComponent
In subcomponent: /Users/marek/Transport-Fever-2-NeonModManager/src/build/Transport Fever 2 NeonModManager.app/Contents/MacOS/modlist.json
~/Transport-Fever-2-NeonModManager
replaced@replaced-iMac Transport-Fever-2-NeonModManager % ransport Fever 2 NeonModManager.app/Contents/MacOS/modlist.json
~/Transport-Fever-2-NeonModManager
``` Do you know what the problem might be? Thank for you help so far.
